version: "3.9"

services:
  key-gen:
    build:
      context: .
      dockerfile: Dockerfile.mongo.init
    volumes:
      - mongo_key:/mnt/shared

  mongo:
    image: mongo:6
    container_name: mongo_db
    hostname: mongo-server
    depends_on:
      key-gen:
        condition: service_completed_successfully
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_key:/data/configdb
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/configdb/keyfile" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-init:
    image: mongo:6
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      mongosh --host mongo-server -u ${MONGO_ROOT_USER} -p ${MONGO_ROOT_PASSWORD} --authenticationDatabase admin --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo-server:27017'}]}) }"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo-server:27017/?authSource=admin&directConnection=true
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_DASHBOARD_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_DASHBOARD_PASSWORD}
    depends_on:
      mongo:
        condition: service_healthy

  backend1:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: poke-albo-backend1
    restart: always
    environment:
      - PORT=${POKEMON_API_1_PORT}
    ports:
      - "${POKEMON_API_1_PORT}:${POKEMON_API_1_PORT}"
    depends_on:
      mongo:
        condition: service_healthy

  backend2:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: poke-albo-backend2
    restart: always
    environment:
      - PORT=${POKEMON_API_2_PORT}
    ports:
      - "${POKEMON_API_2_PORT}:${POKEMON_API_2_PORT}"
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongo_data:
  mongo_key:
